// AUTO-GENERATED from docs/migration/redirect-map.csv — legacy WordPress → new Astro paths.
// Same-domain (emergedigital.com) platform-swap 301s. Regenerate if the map changes.
// Keys are normalized (no trailing slash, except "/"). Worker matches both slash forms.
export const REDIRECTS: Record<string, string> = {
  '/13-reasons-to-hire-a-ppc-agency-in-dubai': '/insights/',
  '/2024-seo-trends': '/insights/',
  '/3-techniques-for-google-tag-manager-testing-a-comprehensive-guide': '/insights/',
  '/3cx': '/services/',
  '/a-b-n-testing': '/insights/',
  '/a-b-testing-vs-multivariate-testing': '/insights/',
  '/about-company': '/about/',
  '/account-based-marketing-funnel': '/insights/',
  '/account-based-marketing-metrics': '/insights/',
  '/account-based-marketing-vs-inbound-marketing': '/insights/',
  '/agency-client-relationships-crucial-for-privacy-centric-strategies': '/insights/',
  '/app-development': '/services/',
  '/app-store-keyword-optimization': '/insights/',
  '/app-store-optimization-android': '/insights/',
  '/b2b-conversion-rate-optimization': '/insights/',
  '/b2b-demand-generation-services': '/services/',
  '/b2b-demand-generation-strategy': '/insights/',
  '/b2b-email-marketing-best-practices': '/insights/',
  '/benefits-of-ecommerce-seo': '/insights/',
  '/benefits-of-local-seo': '/insights/',
  '/blog': '/insights/',
  '/brands-that-prioritize-apps-are-winning-now-and-in-the-future': '/insights/',
  '/case-studies/developing-digital-audience-strategies-for-policy-bazaar-drives-incremental-leads': '/case-studies/',
  '/case-studies/double-revenue-for-ecommerce-vision-eyecare-brand': '/case-studies/',
  '/case-studies/one-year-partnership-that-fostered-community-value': '/case-studies/',
  '/case-study-category/website-development': '/case-studies/',
  '/category/ai': '/insights/',
  '/category/analytics': '/insights/',
  '/category/analytics/page/3': '/insights/',
  '/category/business': '/insights/',
  '/category/google-ads': '/insights/',
  '/category/marketing': '/insights/',
  '/category/marketing/page/2': '/insights/',
  '/category/monitoring': '/insights/',
  '/category/optimization': '/insights/',
  '/category/paid-media': '/insights/',
  '/category/payment-solutions': '/insights/',
  '/category/seo': '/insights/',
  '/category/uncategorized': '/insights/',
  '/category/wordpress': '/insights/',
  '/conversion-rate-optimization-best-practices': '/insights/',
  '/cro-web-analytics': '/services/',
  '/customer-journey-analysis': '/insights/',
  '/customer-journey-optimization': '/services/',
  '/data-analytics-strategy': '/services/',
  '/data-integration-strategy': '/insights/',
  '/data-management-strategy': '/insights/',
  '/data-protection-strategy': '/insights/',
  '/data-unification': '/insights/',
  '/default-redirect-page': '/insights/',
  '/demand-generation-best-practices': '/insights/',
  '/demand-generation-vs-growth-marketing': '/insights/',
  '/deploying-an-ambient-ai-email-assistant': '/insights/',
  '/developing-a-robust-data-governance-strategy': '/insights/',
  '/digital-analytics-measurement-services': '/services/',
  '/display-advertising-programmatic': '/insights/',
  '/ecommerce-facebook-ads': '/insights/',
  '/ecommerce-video-ads': '/insights/',
  '/email-marketing-customer-journey': '/insights/',
  '/email-marketing-mastery-2024': '/insights/',
  '/emerge-digital-now-accepting-crypto-com-pay-payments': '/insights/',
  '/ensuring-your-data-is-accurate-why-you-need-an-analytics-audit': '/insights/',
  '/enterprise-seo-audit': '/insights/',
  '/enterprise-seo-metrics': '/insights/',
  '/everything-you-need-to-know-about-ga4-migration-and-why-it-is-crucial': '/insights/',
  '/first-party-data-strategy': '/insights/',
  '/google-ads-for-ecommerce': '/insights/',
  '/google-analytics-4-audits': '/services/',
  '/google-analytics-4-training': '/services/',
  '/google-analytics-website-traffic': '/insights/',
  '/google-consent-mode-v2-integration': '/insights/',
  '/google-marketing-platform': '/services/google-marketing-platform/',
  '/google-tag-manager-audits': '/services/',
  '/google-tag-manager-vs-google-analytics': '/insights/',
  '/google-tag-monitoring': '/insights/',
  '/google-to-delay-blocking-third-party-cookies-in-chrome-until-2024': '/insights/',
  '/how-can-businesses-benefit-from-using-analytics-on-their-website': '/insights/',
  '/how-can-email-marketing-fuel-your-overall-inbound-strategy': '/insights/',
  '/how-content-marketing-drives-sales': '/insights/',
  '/how-emerge-digital-is-leveraging-ai-to-multiply-impact': '/insights/',
  '/how-long-does-it-take-to-develop-an-app': '/insights/',
  '/how-long-should-a-cold-email-be': '/insights/',
  '/how-long-should-a-marketing-email-be': '/insights/',
  '/how-many-backlinks-per-day-is-safe': '/insights/',
  '/how-many-cold-emails-to-send-per-day': '/insights/',
  '/how-much-does-content-marketing-cost': '/insights/',
  '/how-much-does-email-marketing-cost': '/insights/',
  '/how-much-does-local-seo-cost': '/insights/',
  '/how-much-does-native-advertising-cost': '/insights/',
  '/how-often-should-you-send-marketing-emails': '/insights/',
  '/how-to-calculate-break-even-roas': '/insights/',
  '/how-to-collect-emails-for-email-marketing': '/insights/',
  '/how-to-get-1-2-clients-every-month-for-your-consulting-firm': '/insights/',
  '/how-to-increase-roas': '/insights/',
  '/how-to-manage-your-backlinks': '/insights/',
  '/how-to-optimize-core-web-vitals-for-wordpress-ultimate-guide': '/insights/',
  '/is-content-marketing-dead': '/insights/',
  '/is-cro-a-good-investment': '/insights/',
  '/link-acquisition-the-art-and-science-of-building-high-authority-links': '/insights/',
  '/linkedin-advertising-examples': '/insights/',
  '/linkedin-job-advertising-costs': '/insights/',
  '/local-seo-audit': '/insights/',
  '/marketing-mix-modeling': '/services/',
  '/member-logout': '/insights/',
  '/multivariate-testing-marketing': '/services/',
  '/omnichannel-customer-journey': '/insights/',
  '/paid-media-services': '/services/',
  '/performance-max-campaigns-get-four-new-features-in-google-ads-that-should-get-you-excited': '/insights/',
  '/personalization-strategies-unveiled-how-to-reach-your-ideal-audience-at-the-perfect-time': '/insights/',
  '/portfolio': '/case-studies/',
  '/portfolio-cat/marketing': '/case-studies/',
  '/portfolio-cat/media': '/case-studies/',
  '/portfolio-cat/optimization': '/case-studies/',
  '/portfolio/couriers-by-demand-with-tap-area': '/case-studies/',
  '/portfolio/expandable-video-banners': '/case-studies/',
  '/portfolio/smm-project': '/case-studies/',
  '/portfolio/sydneyelectricalservicebanners': '/case-studies/',
  '/programmatic-video-advertising': '/insights/',
  '/resources': '/insights/',
  '/saas-seo-strategy': '/insights/',
  '/search-engine-marketing-benefits': '/insights/',
  '/search-engine-optimization': '/services/',
  '/sem-ppc-management': '/services/',
  '/seo-strategy-for-multiple-locations': '/insights/',
  '/seo-vs-sem-navigating-the-digital-marketing-maze-for-maximum-visibility': '/insights/',
  '/server-side-tagging-enhances-performance-and-privacy': '/insights/',
  '/strongest-backlinks': '/insights/',
  '/tag/business-app': '/insights/',
  '/tag/google-tag-manager': '/insights/',
  '/tag/mobile-app': '/insights/',
  '/technical-seo-vs-content-seo': '/insights/',
  '/technical-seo-vs-on-page-seo': '/insights/',
  '/thank-you-page': '/insights/',
  '/types-of-account-based-marketing': '/insights/',
  '/understanding-the-digital-customer-journey': '/insights/',
  '/web-governance': '/services/',
  '/what-data-does-google-analytics-prohibit-collecting': '/insights/',
  '/what-data-is-google-analytics-goals-unable-to-track': '/insights/',
  '/what-do-website-analytics-allow-you-to-do': '/insights/',
  '/what-is-a-backlink-profile': '/insights/',
  '/what-is-a-good-ctr-for-linkedin-ads': '/insights/',
  '/what-is-a-good-roas': '/insights/',
  '/what-is-a-secondary-dimension-in-google-analytics': '/insights/',
  '/what-is-cross-network-in-google-analytics': '/insights/',
  '/what-is-enterprise-seo': '/insights/',
  '/what-is-event-count-in-google-analytics': '/insights/',
  '/what-is-pbn-backlinks': '/insights/',
  '/what-is-the-first-step-of-the-data-analytics-process': '/insights/',
  '/what-to-do-after-keyword-research': '/insights/',
  '/which-ecommerce-platform-is-best-for-seo': '/insights/',
  '/why-content-marketing-is-important-for-b2b': '/insights/',
  '/why-is-data-collection-important': '/insights/',
  '/why-is-data-driven-analytics-of-interest-to-companies': '/insights/',
  '/why-it-is-necessary-to-integrate-google-analytics-4-with-bigquery': '/insights/',
  '/why-might-digital-media-be-more-effective-than-television-ads': '/insights/',
  '/why-seo-audit-is-important': '/insights/',
  '/wp-engine': '/services/',
};

// 410 Gone — WooCommerce, WP system, feeds, oauth/payment, legacy assets. Prefix match.
export const GONE_PREFIXES: string[] = [
  '/cart',
  '/checkout',
  '/my-account',
  '/shop',
  '/product',
  '/product-category',
  '/product-tag',
  '/wp-admin',
  '/wp-login',
  '/wp-content',
  '/nitropack_static',
  '/authorize-linkedin',
  '/airwallex',
  '/register',
  '/lost-password',
];

// 410 Gone — pattern match (feeds, xmlrpc).
export const GONE_RE = /(?:^|\/)feed\/?$|xmlrpc/i;
